# Export named camera views from the current ChimeraX session to a portable
# .cxc file under views/<basename>_views.cxc.
#
# Workflow:
#   1. In ChimeraX GUI, load the structure and orient the camera.
#   2. Run `view name <viewname>` for each angle you want to save.
#   3. Run `runscript ../helpers/export_views.py <basename>` from the command
#      line (where <basename> is e.g. 3j2w, 3n42 — only views whose names start
#      with that prefix are exported).
#
# The resulting file contains a `view matrix camera ...` followed by `view name
# ...` for every exported view. Loading it in any other session (via
# helpers/load_views.py or directly with `open views/<basename>_views.cxc`)
# re-creates the named views with their original names intact.

import sys
from pathlib import Path
from chimerax.core.commands import run
from chimerax.std_commands.view import _named_views

if len(sys.argv) < 2:
    raise SystemExit("Usage: runscript export_views.py <basename>")
basename = sys.argv[1]

# Resolve repo root from this file's location so the helper works regardless
# of the caller's working directory.
repo_root = Path(__file__).resolve().parent.parent
views_dir = repo_root / "views"
views_dir.mkdir(exist_ok=True)
out = views_dir / f"{basename}_views.cxc"

nv = _named_views(session)
matching = sorted(name for name in nv.views if name.startswith(basename))

if not matching:
    session.logger.warning(
        f'No named views found with prefix "{basename}". '
        f'Define them first with: view name {basename}_<your_view>'
    )
    raise SystemExit(1)

# Remember the current camera so we can restore it after iterating.
original_matrix = session.main_view.camera.position.matrix.copy()

lines = [
    f"# Camera view definitions for {basename}.",
    f"# Auto-generated by helpers/export_views.py — do not hand-edit.",
    f"# Re-load with: runscript ../helpers/load_views.py {basename}",
    "",
]
for name in matching:
    # Apply the named view, then read the resulting camera matrix from
    # session.main_view.camera. This avoids depending on NamedView's internal
    # attribute names, which vary between ChimeraX versions.
    run(session, f"view {name}")
    matrix = session.main_view.camera.position.matrix
    matrix_str = ",".join(f"{x:.6f}" for x in matrix.flatten())
    lines.append(f"view matrix camera {matrix_str}")
    lines.append(f"view name {name}")
    lines.append("")

# Restore the camera position the user was on before export.
from chimerax.geometry import Place
session.main_view.camera.position = Place(matrix=original_matrix)

out.write_text("\n".join(lines))
session.logger.info(f'Exported {len(matching)} view(s) for "{basename}" to {out}')
